# Generated by Django 4.2.7 on 2025-08-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="code_generation_metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="task",
            name="llm_model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="task",
            name="llm_provider",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="task",
            name="llm_tokens_used",
            field=models.IntegerField(default=0),
        ),
    ]
