# Generated by Django 4.2.7 on 2025-08-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_code_generation_metadata_task_llm_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="last_scheduled_run",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="schedule_cron",
            field=models.CharField(
                blank=True, help_text="Cron expression for scheduling", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="schedule_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
